---
title: "Ogata-Banks 1961"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(aquifer)
library(data.table)
library(plotly)
```

## Solution

Ogata-Banks 1961

## Capabilities

Vectorized calculation of the Ogata-Banks solution.  Does not include retardation or degradation.

```{r ogata, echo = TRUE}
D <- 2
v <- 1
C0 <- 1
x <- seq(1, 120, 2)
t <- seq(0, 80, 10)

ob <- data.table(ogata_banks(D, v, C0, x, t))
setnames(ob, paste0('time_',t))
ob[, x := seq(1, 120, 2)]

```

```{r ogataplot, echo = FALSE, warning=FALSE, message=FALSE}

plot_ly(ob, x = ~x, y = ~time_20, type = 'scatter', mode = 'line', 
        name = 20, width = 700, height = 300) %>% 
  add_lines(x = ~x, y = ~time_40, mode = 'line', name = 40) %>%
  add_lines(x = ~x, y = ~time_60, mode = 'line', name = 60) %>%
  add_lines(x = ~x, y = ~time_80, mode = 'line', name = 80) %>%
  layout(xaxis = list(title = "Distance from source"),
         yaxis = list(side = 'left', title = 'Concentration'))

```

## References

Ogata, A. and Banks, R.B., 1961. A solution of the differential equation of longitudinal dispersion in porous media: fluid movement in earth materials. US Government Printing Office.
