# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' impulse_function
#'
#' @description
#' Calculation of the impulse function from a well function.
#'
#' @param u well function
#' @param flow_time_interval time between flow rate measurements in samples
#'
#' @return impulse function for convolution
#'
#'
#' @export
#'
impulse_function <- function(u, flow_time_interval) {
    .Call('aquifer_impulse_function', PACKAGE = 'aquifer', u, flow_time_interval)
}

#' @title
#' Ogata-Banks solution for 1-D flow.
#'
#' @description
#' Ogata, A., Banks, R.B., 1961. A solution of the differential equation of
#' longitudinal dispersion in porous media. U. S. Geol. Surv. Prof. Pap. 411-A.
#' 1-D, infinite source, uniform flow, constant parameters, no decay, no retardation
#'
#' @param D diffusion coefficient
#' @param v double velocity
#' @param C0 double concentration
#' @param x double x position
#' @param t double time
#'
#' @return ogata banks solution
#'
#' @export
#'
ogata_banks <- function(D, v, C0, x, t) {
    .Call('aquifer_ogata_banks', PACKAGE = 'aquifer', D, v, C0, x, t)
}

#' @title
#' bh_tgamma
#'
#' @description
#' Approximate the gamma function using Boost
#'
#' @param u numeric to evaluate the gamma function
#' @param a numeric flow dimension parameter
#'
#' @return the result of the gamma function
#'
#' @export
bh_tgamma <- function(u, a) {
    .Call('aquifer_bh_tgamma', PACKAGE = 'aquifer', u, a)
}

#' @title
#' bh_gamma_neg
#'
#' @description
#' Approximate the gamma function when a is negative using Boost
#'
#' @param u numeric to evaluate the gamma function
#' @param a numeric flow dimension parameter
#'
#' @return the result of the gamma function
#'
#' @export
bh_gamma_neg <- function(u, a) {
    .Call('aquifer_bh_gamma_neg', PACKAGE = 'aquifer', u, a)
}

#' @title
#' gamma_der
#'
#' @description
#' Derivative of the gamma function.
#'
#' @param u numeric to evaluate the gamma function
#' @param a numeric flow dimension parameter
#'
#' @return the result of the gamma function
#'
#' @export
gamma_der <- function(u, a) {
    .Call('aquifer_gamma_der', PACKAGE = 'aquifer', u, a)
}

#' @title
#' exp_int_single
#'
#' @description
#' Calculate the exponential integral using Boost
#'
#' @param u value of the Theis u
#' @param a not used (flow dimension)
#'
#' @return exponential integral
#'
#' @useDynLib aquifer
#' @import RcppParallel
#' @importFrom Rcpp evalCpp
#'
#' @export
#'
exp_int_single <- function(u, a) {
    .Call('aquifer_exp_int_single', PACKAGE = 'aquifer', u, a)
}

#' @title
#' grf_parallel
#'
#' @description
#' Parallel vector version of the exponential integral
#'
#' @param u value of the Theis u
#' @param a flow dimension
#'
#' @return exponential integral
#'
#'
#' @export
#'
grf_parallel <- function(u, a) {
    .Call('aquifer_grf_parallel', PACKAGE = 'aquifer', u, a)
}

#' @title
#' bessel_k
#'
#' @description
#' boost function for the Bessel function
#'
#' @param u value for bessel function
#'
#' @return result of the bessel function
#'
#'
#' @export
#'
bessel_k <- function(u) {
    .Call('aquifer_bessel_k', PACKAGE = 'aquifer', u)
}

#' @title
#' hantush_well_single
#'
#' @description
#' Result of the hantush well function
#'
#' @param u value of the Theis u
#' @param b the leakance
#' @param n_terms the number of terms used in the hantush approximation
#'
#'
#' @return hantush well function
#'
#'
#' @export
#'
hantush_well_single <- function(u, b, n_terms) {
    .Call('aquifer_hantush_well_single', PACKAGE = 'aquifer', u, b, n_terms)
}

#' @title
#' hantush_well_single
#'
#' @description
#' Parallel version of the hantush well function
#'
#'
#' @param u (vector) value of the Theis u
#' @param b the leakance
#' @param n_terms the number of terms used in the hantush approximation
#'
#'
#' @return hantush well function
#'
#'
#' @export
#'
hantush_well_parallel <- function(u, b, n_terms) {
    .Call('aquifer_hantush_well_parallel', PACKAGE = 'aquifer', u, b, n_terms)
}

#' @title
#' well_function_coefficient
#'
#' @description
#' Calculation Coefficient Q/(4 pi * T)
#'
#' @param flow_rate well flow rates
#' @param transmissivity aquifer transmissivity
#'
#' @return coefficient for Theis and Hantush well function
#'
#'
#' @export
#'
well_function_coefficient <- function(flow_rate, transmissivity) {
    .Call('aquifer_well_function_coefficient', PACKAGE = 'aquifer', flow_rate, transmissivity)
}

#' @title
#' hantush_epsilon
#'
#' @description
#' Calculation of r^2/(4B^2)
#'
#' @param radius distance to monitoring well
#' @param leakage aquifer transmissivity
#'
#' @return coefficient Hantush well function
#'
#'
#' @export
#'
hantush_epsilon <- function(radius, leakage) {
    .Call('aquifer_hantush_epsilon', PACKAGE = 'aquifer', radius, leakage)
}

#' @title
#' grf_coefficient
#'
#' @description
#' Coefficient for the grf without pumping
#'
#' @param flow_rate (vector) the flow rate
#' @param radius (double) distance to center of source
#' @param K (double) hydraulic conductivity of the fracture system
#' @param thickness (double) thickness
#' @param flow_dimension (double) flow dimension
#'
#' @return coefficient
#'
#'
#' @export
#'
grf_coefficient <- function(flow_rate, radius, K, thickness, flow_dimension) {
    .Call('aquifer_grf_coefficient', PACKAGE = 'aquifer', flow_rate, radius, K, thickness, flow_dimension)
}

#' @title
#' theis_u_time
#'
#' @description
#' Calculation of Theis u
#'
#' @param radius distance to monitoring interval
#' @param storativity aquifer storativity
#' @param transmissivity aquifer transmissivity
#' @param time prediction times
#'
#' @return u for well function
#'
#'
#' @export
#'
theis_u_time <- function(radius, storativity, transmissivity, time) {
    .Call('aquifer_theis_u_time', PACKAGE = 'aquifer', radius, storativity, transmissivity, time)
}

#' @title
#' well_function_convolve
#'
#' @description
#' Parallel convolution in the time domain
#'
#' @param flow_time_interval time between flow rate measurements in samples
#' @param coefs well coeffiicents
#' @param u well impuse function
#'
#' @return impulse function for convolution
#'
#'
#' @export
#'
well_function_convolve <- function(flow_time_interval, coefs, u) {
    .Call('aquifer_well_function_convolve', PACKAGE = 'aquifer', flow_time_interval, coefs, u)
}

#' @title
#' grf_time_parallel
#'
#' @description
#' Parallel convolution of Theis well function and flow rates in the time domain.
#' Time series needs to be regularily spaced.
#'
#' @param radius distance to monitoring interval
#' @param storativity aquifer storativity
#' @param K aquifer hydraulic conductivity
#' @param thickness aquifer thickness
#' @param time prediction times
#' @param flow_rate well flow rates
#' @param flow_time_interval time between flow rate measurements in samples
#' @param flow_dimension time between flow rate measurements in samples
#'
#' @return theis solution for multiple pumping scenario
#'
#'
#' @export
#'
grf_time_parallel <- function(radius, storativity, K, thickness, time, flow_rate, flow_time_interval, flow_dimension) {
    .Call('aquifer_grf_time_parallel', PACKAGE = 'aquifer', radius, storativity, K, thickness, time, flow_rate, flow_time_interval, flow_dimension)
}

#' @title
#' hantush_time_parallel
#'
#' @description
#' Parallel convolution of hantush well function and flow rates in the time domain.
#' Time series needs to be regularily spaced.
#'
#' @param radius distance to monitoring interval
#' @param storativity aquifer storativity
#' @param transmissivity aquifer transmissivity
#' @param leakage hantush leakage
#' @param time prediction times
#' @param flow_rate well flow rates
#' @param flow_time_interval time between flow rate measurements in samples
#' @param n_terms number of terms to use in Hantush solution.  More is more precise but slower.
#'
#' @return hantush jacob solution for multiple pumping scenario
#'
#'
#' @export
#'
hantush_time_parallel <- function(radius, storativity, transmissivity, leakage, time, flow_rate, flow_time_interval, n_terms) {
    .Call('aquifer_hantush_time_parallel', PACKAGE = 'aquifer', radius, storativity, transmissivity, leakage, time, flow_rate, flow_time_interval, n_terms)
}

